# Generated by Django 5.2.4 on 2025-08-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20250806_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetype',
            name='slug',
            field=models.SlugField(max_length=50, unique=True),
        ),
    ]
